[package]
name = "keyv-core"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features = ["rt-multi-thread", "macros", "parking_lot", "net", "fs", "io-util", "sync", "time"] }
async-trait = "0.1.88"

eyre = "0.6.12"